# Generated by Django 6.0.4 on 2026-04-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='target_price',
        ),
    ]
